name: test3
channels:
  # - bioconda
  - conda-forge
dependencies: #Having some clobberErros and VerificationError (plotly seems corrupted in mac)
  - python  #ALLarch
  - pip  #ALLarch
  - r-base  #ALLarch
  - numpy #ALLarch
  - pandas  #ALLarch
  - scikit-learn  #ALLarch
  - pynndescent #ALLarch
  - umap-learn #ALL64arch
  - plotly #noarch
  - bioconda::scprep #noarch
  - bioconda::fcsparser #noarch
  - rpy2 #ALL64arch
  - r-rcolorbrewer #noarch
  - r-plotly #noarch
  - r-dt #noarch
  - r-ggally #noarch
  - r-psych  #noarch
  - r-hmisc  #noarch
  - r-mass #noarch
  - r-factominer #noarch
  - r-factoextra #noarch
  - r-matrixstats  #noarch
  - r-tidyverse  #noarch
  - r-shiny #noarch
  - bioconda::bioconductor-flowcore #linos64
  - bioconda::bioconductor-complexheatmap #noarch
  - pip:
    - fcswrite
  #   - rpy2