name: cygnal_test
channels:
  # - bioconda
  - conda-forge
dependencies: #Having some clobberErros and VerificationError (plotly seems corrupted in mac)
  - python=3.8  #ALLarch -> Installs to 3.8.8 in macOS
  - pip  #ALLarch
  - r-base=4.0  #ALLarch -> Installs to 4.0.3 in macOS
  - numpy #ALLarch
  - pandas  #ALLarch
  - scikit-learn  #ALLarch
  - pynndescent #ALLarch
  - umap-learn #ALL64arch
  - plotly #noarch
  - bioconda::scprep #noarch
  - bioconda::fcsparser #noarch
  - rpy2 #ALL64arch
  - r-rcolorbrewer #noarch
  - r-plotly #noarch
  - r-dt #noarch
  - r-ggally #noarch
  - r-psych  #noarch
  - r-hmisc  #noarch
  - r-mass #noarch
  - r-factominer #noarch
  - r-factoextra #noarch
  - r-matrixstats  #noarch
  - r-tidyverse  #noarch
  - r-shiny #noarch
  - r-biocmanager
  - bioconda::bioconductor-flowcore #-> Installs but now fails to load on macOS -> compilation issue
  - bioconda::bioconductor-complexheatmap #noarch
  - bioconda::bioconductor-cytolib #Manually state dependencies for flowcore
  - bioconda::bioconductor-rprotobuflib #Manually state dependencies for flowcore
  - pip:
    - fcswrite

