name: cygnal
channels:
  # - bioconda
  - conda-forge
dependencies: 
  - python=3.8  
  - pip=21  
  - r-base=4.0
  - natsort  
  - numpy #ALLarch
  - pandas  #ALLarch
  - scikit-learn  #ALLarch
  - pynndescent #ALLarch
  - umap-learn #ALL64arch
  - plotly #noarch
  - bioconda::scprep #noarch
  - bioconda::fcsparser #noarch
  - rpy2=3.4 #ALL64arch
  - r-rcolorbrewer #noarch
  - r-plotly #noarch
  - r-dt #noarch
  - r-ggally #noarch
  - r-psych  #noarch
  - r-hmisc  #noarch
  - r-mass #noarch
  - r-factominer #noarch
  - r-factoextra #noarch
  - r-matrixstats  #noarch
  - r-tidyverse  #noarch
  - r-shiny #noarch
  - r-ggrepel #in conda-forge
  - bioconda::bioconductor-complexheatmap #noarch
  - bioconda::bioconductor-flowcore=2.2.0 
  - bioconda::bioconductor-cytolib=2.2.1 #2.2.1 set on 01/05/21
  - pip:
    - fcswrite

