name: cygnal
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - pip=20   
  - r-base>=4
  - r-essentials
  - numpy
  - pandas
  - scikit-learn #Added sklearn from main conda channel
  - pynndescent #Should be in conda-forge
  - umap-learn #In conda-forge, moved to conda from pip
  - plotly
  - scprep
  - rpy2
  - r-rcolorbrewer
  - r-plotly
  - r-dt
  - r-ggally
  - r-psych
  - r-hmisc
  - r-mass
  - r-factominer
  - r-factoextra
  - r-matrixstats
  - bioconductor-flowcore
  - bioconductor-complexheatmap

  - pip:
    - fcsparser
    - fcswrite
    # - sklearn Changed to conda
    # rpy2 R dependencies are accesible only if rpy2 is installed trhough conda
    # - umap-learn Changed to conda

#TODO: Add complexheatmap and possilby new UMAP dependencies
